### PR TITLE
Update tslint

### PR DESCRIPTION
**Pull request by pigeonfresh**
Allow parameter reassignment

### CODE REVIEW

**Comment by pigeonfresh** [comment]
Not allowing paramaters to be reassigned by TSLint will throw a lint error when using Vue Transition Component. This rule was already disabled in ESLint.

**Comment by petervdn** [comment]
What is an example of code that breaks then? (es or ts)

**Comment by pigeonfresh** [comment]
```
The 'no-parameter-reassignment' rule threw an error in '/Users/eelkevdbij/Projects/etc'
TypeError: ts.unescapeIdentifier is not a function
```

**Comment by petervdn** [comment]
That's the error itself, what exactly causes it? I don't really support fully disabling a rule projectwide for everyone just because there apparently is an issue with it in certain cases. Can't you just disable the rule for certain lines?

**Comment by ThaNarie** [comment]
Looks like there are two different reasons mentioned:
1) it was already disabled in eslint (still want to know why)
2) it throws a runtime error because of a TS 3.0 breaking change (this should have been mentioned in the commit message)

**Comment by pigeonfresh** [comment]
@petervdn the transition controller of Vue transition component causes the error

**Comment by flut1** [comment]
This seems to be resolved by updating tslint (the package, not the config). See palantir/tslint#4016

**Pull request closed without merging**
