### PR TITLE
Shared variables between JS/SCSS

### PR DESCRIPTION
**Pull request by jesse-mm**
A lot of MM projects already use sassify-webpack plugin for sharing variables. Since newer releases of webpack this became a bit buggy.

This PR will add node-sass-json-importer for node-sass. This allows sharing variables using JSON with node-sass. Previously intergration with node-sass-json-importer this wasn't [possible](https://github.com/vuejs/vue-loader/issues/967) due to the `vue-loader`. The new version of vue-loader supports passing objects to other loaders.

To get all this working, I needed to removed extract-text-webpack-plugin (beta status) [reasoning](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/749)) with mini-css-extract-plugin. Also upgraded webpack to 4.4.x so it's compatible with mini-css-extract-plugin.

**Note** Maybe it's even a good idea to update webpack to the latest version

### CODE REVIEW

**Comment by jesse-mm** [comment]
@ThaNarie I was thinking to leave out mediaQueries in JSON. Just wanted to have shared-variables stub so people can add their own ones. We could opt for some default ones;

After the PR merge I'll update the docs on the wiki about using shared-variables.json where I can mention and have an example of integration with DeviceStateTracker.

**Comment by ThaNarie** [comment]
Not sure if we want/need a `data/shared-variables.json`, each different type of variables could have its own json file?

**Comment by jesse-mm** [comment]
True that; We could remove it from utils.scss and just add a proper description on using this functionality in the wiki.

**Comment by hjeti** [comment]
Looks good to me.

**Comment by jesse-mm** [comment]
I've this PR with latest `webpack` and `mini-css-extract-plugin` and made media queries 'shared' by default.

Docs (will be added to the wiki once merged)

# Sharing variables between JavaScript and SASS
Vue skeleton comes with the [node-sass-json-importer](https://github.com/Updater/node-sass-json-importer) support. The skeleton imports by default `mediaQueries.json` which contains a standard set of media queries. This setup plays nicely with the respond-to mixin provided by [seng-scss](https://github.com/mediamonks/seng-scss).

## Using mediaQueries together with [seng-device-state-tracker](https://github.com/mediamonks/seng-device-state-tracker)
To use seng-device-state-tracker make sure it is installed first. Add it by running `yarn add seng-device-state-tracker`. A simple example setup using `mediaQueries.json` together with seng-device-state-tracker.

`startUp.js`
```
import { mediaQueries } from 'data/mediaQueries.json';

...
Vue.use(VueExposePlugin, {
    // ... other exposed variables to the VueInstance
    $deviceStateTracker: new DeviceStateTracker({
      mediaQueries,
      deviceState: Object.keys(mediaQueries).reduce(
        (mediaQueryList, mediaQueryName, index) => ({
          ...mediaQueryList,
          [mediaQueryName]: index,
        }),
        {},
      ),
      showStateIndicator: process.env.NODE_ENV !== 'production',
    }),
});
```

More information on usage can be found on here [seng-device-state-tracker](https://github.com/mediamonks/seng-device-state-tracker).

**Comment by hjeti** [comment]
Looks good to me.

**Pull request merged**
